[package]
name = "dzip-core"
version.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
byteorder = "1.5.0"
bzip2 = "0.6.1"
flate2 = "1.1.8"
lzma-rs = "0.3.0"
thiserror = "2.0.18"
log.workspace = true
serde.workspace = true
